name: matrix-test

on:
  push:

jobs:
  build-container:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        accounts: [account1, account2]
        tags: [1,2,3]
    steps:
      - run: echo "${{ matrix.accounts }}:${{ matrix.tag }}"
