name: matrix-test

on:
  push:

jobs:
  build-container:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        account: [account1, account2]
        include: 
          - account: account1
            tag: [1,2,3]
          - account: account2
            tag: [1,2,3]
    steps:
      - run: echo "${{ matrix.account }}:${{ matrix.tag }}"
